### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by matthewbaggett** [Sterling-Technologies/eden#22]
Can you appoint some new maintainers?

**Comment by SlimDeluxe** [comment]
He seems still active on Github, but for some reason not in this project since january. Hopefully they'll come back or someone else will fork and keep maintaining it.

**Comment by sbalignasay** [comment]
Hi Guys, we will gonna be updating Eden soon. We're just trying to finish some things

**Comment by vijinho** [comment]
Is this project still active or should I ignore it and use some other project?

**Comment by ilbonzo** [comment]
Can we define inactive this project?

**Comment by cblanquera** [comment]
This version of eden maybe forked. No problem. Most of our efforts moved to https://github.com/Eden-PHP to match FIG and Composer requirements. We also have been replicating this on Node https://github.com/edenjs . just ping me on FB https://www.facebook.com/christian.blanquera if you need anything else.

**Comment by ilbonzo** [comment]
thanks for the response
