### ISSUE TITLE
Integrating with Zend Framework

### ISSUE THREAD

**Issue by OptimusMarlboro** [Sterling-Technologies/eden#5]
Hi,

Is there any documentation about integrating Eden with Zend Framework 1?

**Comment by cblanquera** [comment]
Hey Optimus, we have a dev here using Eden on ZF1, but today is a holiday for us, I'll have him blog about it on tuesday.

**Comment by nikkobautista** [comment]
@OptimusMarlboro What kind of integration are you looking to do? I might be able to help you out.

**Comment by OptimusMarlboro** [comment]
@cblanquera I'd love to read that blog. Please let us know the url when it's availabke.
@nikkobautista I was talking about autoloading. As all folder names and file names are all lowercase, I was getting class not found error (e.g. Eden_facebook not found). I put `$file = strtolower($file);` in loader.php line 92, all seems to be working fine now.

**Comment by nikkobautista** [comment]
@OptimusMarlboro okay, cool. You might want to make use of ZF's Autoloader to autoload the Eden files, just register one in Bootstrap.php and you sohuld be good to go as well.

**Comment by cblanquera** [comment]
Hey Optimus as promised, http://openovate.com/startup/eden-library-on-zend-framework/

Will leave this issue open for a couple more days.
